name: StackOverflow Daily Login

on:
  schedule:
    - cron: '0 8 * * *'  # This triggers the workflow at 8:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Create login_to_stackoverflow.py script
        run: |
          echo "import requests" > login_to_stackoverflow.py
          echo "from bs4 import BeautifulSoup" >> login_to_stackoverflow.py
          echo "" >> login_to_stackoverflow.py
          echo "username = '${{ secrets.STACKOVERFLOW_EMAIL }}'" >> login_to_stackoverflow.py
          echo "password = '${{ secrets.STACKOVERFLOW_PASSWORD }}'" >> login_to_stackoverflow.py
          echo "" >> login_to_stackoverflow.py
          echo "def login_to_stackoverflow():" >> login_to_stackoverflow.py
          echo "    login_url = 'https://stackoverflow.com/users/login'" >> login_to_stackoverflow.py
          echo "    session = requests.Session()" >> login_to_stackoverflow.py
          echo "" >> login_to_stackoverflow.py
          echo "    response = session.get(login_url)" >> login_to_stackoverflow.py
          echo "    soup = BeautifulSoup(response.text, 'html.parser')" >> login_to_stackoverflow.py
          echo "" >> login_to_stackoverflow.py
          echo "    fkey = soup.find('input', {'name': 'fkey'})['value']" >> login_to_stackoverflow.py
          echo "" >> login_to_stackoverflow.py
          echo "    payload = {" >> login_to_stackoverflow.py
          echo "        'fkey': fkey," >> login_to_stackoverflow.py
          echo "        'email': username," >> login_to_stackoverflow.py
          echo "        'password': password" >> login_to_stackoverflow.py
          echo "    }" >> login_to_stackoverflow.py
          echo "" >> login_to_stackoverflow.py
          echo "    login_response = session.post(login_url, data=payload)" >> login_to_stackoverflow.py
          echo "" >> login_to_stackoverflow.py
          echo "    if 'Logout' in login_response.text:" >> login_to_stackoverflow.py
          echo "        print('Login successful!')" >> login_to_stackoverflow.py
          echo "    else:" >> login_to_stackoverflow.py
          echo "        print('Login failed.')" >> login_to_stackoverflow.py
          echo "        print(login_response.text)" >> login_to_stackoverflow.py
          echo "" >> login_to_stackoverflow.py
          echo "if __name__ == '__main__':" >> login_to_stackoverflow.py
          echo "    login_to_stackoverflow()" >> login_to_stackoverflow.py

      - name: Run login script
        env:
          STACKOVERFLOW_EMAIL: ${{ secrets.STACKOVERFLOW_EMAIL }}
          STACKOVERFLOW_PASSWORD: ${{ secrets.STACKOVERFLOW_PASSWORD }}
        run: python login_to_stackoverflow.py
