name: StackOverflow Daily Login

on:
  schedule:
    - cron: '0 8 * * *'  # This triggers the workflow at 7:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Create run_at_random_time.sh
        run: |
          echo '#!/bin/bash' > run_at_random_time.sh
          echo '' >> run_at_random_time.sh
          echo '# Generate a random minute between 0 and 59' >> run_at_random_time.sh
          echo 'RANDOM_MINUTE=$(shuf -i 0-59 -n 1)' >> run_at_random_time.sh
          echo 'echo "Generated random minute: $RANDOM_MINUTE"' >> run_at_random_time.sh
          echo '' >> run_at_random_time.sh
          echo '# Wait until the random minute within the 7 AM hour' >> run_at_random_time.sh
          echo 'SLEEP_TIME=$(( (60 - $(date +%M) + RANDOM_MINUTE) % 60 * 60 ))' >> run_at_random_time.sh
          echo 'echo "Sleeping for $SLEEP_TIME seconds..."' >> run_at_random_time.sh
          echo 'sleep $SLEEP_TIME' >> run_at_random_time.sh
          echo '' >> run_at_random_time.sh
          echo '# Run the login script' >> run_at_random_time.sh
          echo 'python login_to_stackoverflow.py' >> run_at_random_time.sh
          chmod +x run_at_random_time.sh

      - name: Run at 8:00 AM local time
        env:
          STACKOVERFLOW_EMAIL: ${{ secrets.STACKOVERFLOW_EMAIL }}
          STACKOVERFLOW_PASSWORD: ${{ secrets.STACKOVERFLOW_PASSWORD }}
        run: ./run_at_random_time.sh
